### ISSUE TITLE
No means to set /SetPlatformServerAdminPassword with ConfigurationTool

### ISSUE THREAD

**Issue by SmartPlugins** [OutSystems/OutSystems.SetupTools#58]
No option/parameter found to set the ConfigurationTool with the command switch /SetPlatformServerAdminPassword to set/reset the ServerAdminPassword in Set-OSSServerConfig

**Comment by pintonunes** [comment]
Hi @SmartPlugins ,

We didnt had the /SetPlatformServerAdminPassword to the configuration tool cause you can set the password like:
```
Set-OSServerConfig -SettingSection 'ServerConfiguration' -Setting 'PlatformServerAdminPassword' -Value 'whatever'
```
and then use:
```
Set-OSServerConfig -Apply -InstallServiceCenter
```

Just a remark. To set the password you need to add the switch -InstallServiceCenter on the -Apply mode.

Is this enough for your use case?
