### ISSUE TITLE
Unattended script fails

### ISSUE THREAD

**Issue by vidarak** [OutSystems/OutSystems.SetupTools#59]
The unattended script fails. It's missing critical parts like setting the PlatformServerAdminPassword and applying configuration with -InstallServiceCenter parameter (which is required when applying the configuration apparently).

**Comment by pintonunes** [comment]
Hi @vidarak,

Sorry for the huge delay on this. You need to set the password before.
Check #58

**Comment by vidarak** [comment]
How can one set adminpassword with Set-OSServerConfig before installing Outsystems unattended?

**Comment by pintonunes** [comment]
You can:
Install-OSServer (installs OutSystems)
Set-OSServerConfig -SettingSection 'ServerConfiguration' -Setting 'PlatformServerAdminPassword' -Value 'whatever'
Set-OSServerConfig -Apply -InstallServiceCenter

**Comment by vidarak** [comment]
Pedro, I hope you realize this issue is about the script here:
https://github.com/OutSystems/OutSystems.SetupTools/blob/dev/examples/FullUnattended/outsystemsSetupScript.ps1
It's literally called "FullUnattended" and the expectation is exactly so; running that script should do a full unattended installation of outsystems without having to execute additional commands.

**Comment by pintonunes** [comment]
Yes, I understand. 
We have that script as an example only on how to use this module. We don't maintain the script. 
The script was build for a previous version of OutSystems where you didn't had to provide a password for Service Center. In the latest OutSystems versions you need to.

To make that script work again you need to add this line:
`Set-OSServerConfig -SettingSection 'ServerConfiguration' -Setting 'PlatformServerAdminPassword' -Value 'whatever'` between line 126-143
Also you need to add the `-InstallServiceCenter` to line 171 and 175.

PRs are welcome if you want to contribute.
