### ISSUE TITLE
RabbitMQ installation should be skipped but isn't

### ISSUE THREAD

**Issue by rodamber** [OutSystems/OutSystems.SetupTools#69]
Hi guys, I'm getting strange behavior when doing a FullInstall:

![image](https://user-images.githubusercontent.com/8083887/78058322-067bb480-7380-11ea-92d2-75e5d81cc476.png)

Were there any recent changes that might have caused this? 

FYI, recently I enabled the -SkipRabbitMQ switch when calling Install-OSServer on setuptools-internal ([link](https://github.com/OutSystems/OutSystems.SetupTools-Internal/pull/22/commits/8639fb9816e5d9edbb047ce046c15dbab35c7e69)), and I don't remember getting this behavior then (although I might have just not seen it).

**Comment by pintonunes** [comment]
Hi @rodamber sorry for the delay.
From the logs looks like a bug. But let me check

**Comment by rodamber** [comment]
Hi @pintonunes, I'm failing to reproduce this since Friday, so you might want to close the issue. 😕

**Comment by pintonunes** [comment]
Ok @rodamber, closing now. Anyway, thanks for the feedback!
