### ISSUE TITLE
Unable to install lifetime with higher version than 11.0

### ISSUE THREAD

**Issue by mpsanten** [OutSystems/OutSystems.SetupTools#80]
The following command should publish the lifetime solution: 
Publish-OSPlatformLifetime -Credential $OSPlatformCred  

But this exits with error:  
Publish Error : Error publishing to 'acc-lifetime01': ssServiceCenter.ExcptGeneralError: LifeTime component not licensed.

This is of-course correct,, but I can't create a license file before I start the full installation script as I don't have the serial number of the server at the start of the script.  It looks like with 11.0 there was a 30 day trial so the script could at least finish after which you can fix the license. Now with the newer version that option is gone.

**Comment by pintonunes** [comment]
Hi @mpsanten, you're right. We will replace the trial license with a new one that can install LT 11.X.

**Comment by mpsanten** [comment]
Thanks for your quick reaction. I suppose it will be in the next release ?!   I'm happy to test it once it's there.

**Comment by pintonunes** [comment]
Its already fixed :) 
Closing the issue. Please reopen if needed.
Thanks for reporting!
