### ISSUE TITLE
Install-OSPlatformLicense gives warning

### ISSUE THREAD

**Issue by MennoBroxterman** [OutSystems/OutSystems.SetupTools#83]
[PROCESS]  Installing outsytems license
[PROCESS]  Service Center Installer version 11.9.1 build 20359
[PROCESS]  
[PROCESS]  WARNING : The '/UploadLicense LICENSE_FILE' command-line option has 
been deprecated.
[PROCESS]  Use the following option instead:
[PROCESS]  ConfigurationTool /UploadLicense LICENSE_FILE SERVICE_CENTER_USER 
SERVICE_CENTER_PASSWORD

**Comment by pintonunes** [comment]
Hi @MennoBroxterman, yes we know and this is planned for changing.
Anyway, thanks for reporting
