### ISSUE TITLE
Can't update Lifetime server

### ISSUE THREAD

**Issue by calford3075** [OutSystems/OutSystems.SetupTools#88]
We have our Lifetime Server on 11.5.0.223
We have tried to upgrade to Lifetime Server Version 11.7.1.748
The command we are using is:
Install-OSServer -Version 11.7.1.748 -InstallDir $InstallDir -WithLifetime -SkipRabbitMQ -Verbose -ErrorAction Stop | Out-Null
and we got this error:
ERROR   : 2021-01-21 09:01:27.4304 [Install-OSServer                        ]  [PROCESS]  OutSystems platform server already installed with an higher version 11.7.3.7036

It appears to be due to the fact that it is comparing the Version parameter we send into the Install-OSServer function to the current installed Platform Server Version, not the current installed LifeTime Version (Platform Server that is installed with Lifetime 11.5.0.223 is actually 11.7.3.7036)

**Comment by pintonunes** [comment]
Hi @calford3075, yes its a bug. Thanks for reporting. Will fix it.

**Comment by pintonunes** [comment]
Fixed on the 3.9.0.0 version. Please reopen the issue if is not the case.
