### ISSUE TITLE
Publish-OSPlatformLifetime is setting lifetime registry entry to Platform Server version

### ISSUE THREAD

**Issue by calford3075** [OutSystems/OutSystems.SetupTools#89]
In the Publish-OSPlatformLifetime function it is getting the platform server version, not the lifetime version, so when it writes to the registry entry -Path "HKLM:SOFTWARE\OutSystems\Installer\Server" -Name "LifeTime" it is setting it with the wrong version causing the function to error when updating.

**Comment by pintonunes** [comment]
Will check that also.. Thanks for reporting

**Comment by calford3075** [comment]
Thank you for looking into this, was just wondering if there was any progress?

**Comment by pintonunes** [comment]
Sorry for the delay @calford3075. We will fix the issue asap

**Comment by pintonunes** [comment]
Should be fixed in 3.10.1.0. Reopen if otherwise.
